[default.extend-words]
hax = "hax"
hsi = "hsi"
extint = "extint"     # External interrupt
synopsys = "synopsys" # Manufacturer name
COSE = "COSE"         # A technology we use

negativ = "negativ" # Typo in a branch name in ariel-os-cargo.toml

[default.extend-identifiers]
celcius = "celcius" # Until embedded-aht20 is fixed

[files]
extend-exclude = ["doc/*.svg", "src/ariel-os-rp/src/cyw43/firmware/README.md"]
