[package]
name = "usb-serial"
license.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
ariel-os = { path = "../../src/ariel-os", features = ["override-usb-config"] }
ariel-os-boards = { path = "../../src/ariel-os-boards" }
