name: Preview PR docs

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Deploy docs"]
    types:
      - completed

jobs:
  preview:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/download-artifact@v4
        with:
          name: pr-${{ github.event.workflow_run.event.number }}-docs
          path: ./_site

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install surge
        run: npm --global install surge

      - name: Deploy PR preview
        run: |
          surge ./_site ${{ github.repository_owner }}-docs-preview-pr${{ github.event.workflow_run.event.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Comment URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.workflow_run.event.number }}
          message: |
            🚀 PR preview deployed to <https://${{ github.repository_owner }}-docs-preview-pr${{ github.event.workflow_run.event.number }}.surge.sh>
